# Generated by Django 4.0.6 on 2022-07-22 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_author_alter_article_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 14, 1, 50, 668135, tzinfo=utc)),
        ),
    ]
